### ISSUE TITLE
changing font in yaml does not change the font in the document

### ISSUE THREAD

**Issue by faebser** [jez/pandoc-starter#7]
I have the following yaml inside my md file. producing the pdf does not generate an error or anything else for the fonts.

```yaml
---
documentclass: tufte-handout
title: "Summary Chapter 11: Art and Telematics"
author: foo
date: \today
fontsize: 12pt
# Comment or change these if you don't have these fonts installed
mainfont: IBM Plex Mono Regular
monofont: IBM Plex Mono Regular
newtxmathoptions:
- cmintegrals
- cmbraces
colorlinks: true
linkcolor: RoyalBlue
urlcolor: RoyalBlue
---
```
